plugins {
    id 'com.android.application'
}

android {
    namespace 'com.downpour'
    compileSdk 34
    ndkVersion '28.2.13676358'

    defaultConfig {
        applicationId "com.downpour"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.1.8-android"

        ndk {
            abiFilters 'arm64-v8a'
        }

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++23", "-fexceptions", "-frtti",
                         "-O3", "-fvectorize", "-fslp-vectorize",
                         "-funroll-loops", "-fno-semantic-interposition",
                         "-flto=thin", "-DNDEBUG"
                arguments "-DANDROID_STL=c++_shared",
                          "-DANDROID_PLATFORM=android-26",
                          "-DDPOUR_NO_NATIVE_RENDER=1",
                          "-DCMAKE_BUILD_TYPE=Release",
                          "-DCMAKE_SHARED_LINKER_FLAGS=-flto=thin -Wl,-O3 -Wl,--gc-sections -Wl,--icf=all -Wl,--hash-style=gnu -Wl,-Bsymbolic-functions -Wl,-z,max-page-size=16384"
            }
        }
    }

    buildTypes {
        debug {
            debuggable true
            jniDebuggable true
        }
        release {
            minifyEnabled false
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path file('../CMakeLists.txt')
            version '3.22.1'
        }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['src/main/jniLibs']
        }
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.10.0'
}
